language: php

php:
    - 5.5
    - 5.6
    - 7.0
    - 7.1
    - 7.2
    - 7.3

before_script:
    - composer self-update
    - composer install

script:
    - vendor/bin/phpunit --coverage-clover coverage.clover
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

branches:
    only:
        - master

matrix:
    allow_failures:
        - php: 7.0
